### PR TITLE
rename repo to dagger-for-github

### LINKED ISSUE #21: Rename `dagger-action` to something less confusing
## Problem

From the point of view of a Github Actions user, "dagger-action" makes perfect sense. But from the point of view of the Dagger community, it is confusing: is it a product called "action" by Dagger? Is it a way to perform an action in Dagger? Is it a clone of Github Actions by Dagger?

## Solution

After discussion: the most pragmatic solution seems to be renaming this repo to `dagger-for-github`.

## Alternative options

The following options were discussed:

> 1. Borrowing from Docker's edition model: `dagger-for-github`
> 2. Another variation on the edition model: `dagger-on-github`
> 3. Minimalist variatin: `dagger-github`
> 4. Same idea but more specific: `dagger-gha`
> 
> My preference right now is option 1: `dagger-for-github`. Simply because the format of "Docker for Mac", "Github for Mac" (fun fact: this is the inspiration for D4M :) is familiar to many developers.

### PR DESCRIPTION
**Pull request by crazy-max**
fixes #21 

@shykes @aluzzardi would temporary need admin rights to the repo to rename it when merged and also check everything is ok in the actions marketplace.

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

**Review by aluzzardi — APPROVED** [review]

**Comment by aluzzardi** [comment]
> @shykes @aluzzardi would temporary need admin rights to the repo to rename it when merged and also check everything is ok in the actions marketplace.

Done!

Thank you!

**Comment by crazy-max** [comment]
@aluzzardi I merge this one and will debrief with @grouville about the process.

**Comment by crazy-max** [comment]
@grouville We might also change the action name:

https://github.com/dagger/dagger-for-github/blob/2e5f57a90b1fd846ab90c865cd143aef6452000a/action.yml#L1

to `Dagger for GitHub` so link in the marketplace would be https://github.com/marketplace/actions/dagger-for-github.

**Comment by shykes** [comment]
In the context of Github marketplace, it kind of makes sense that it would be https://github.com/marketplace/actions/dagger  seems more natural

Does that compatible with keeping the dagger-for-github name elsewhere, or will it confuse users?

**Comment by crazy-max** [comment]
> In the context of Github marketplace, it kind of makes sense that it would be https://github.com/marketplace/actions/dagger seems more natural

We can't unfortunately. Name in marketplace is tied to username/orgname on GitHub so we can't pick `/dagger` as it's already used by dagger itself :sweat_smile:.

**Comment by shykes** [comment]
Makes sense. I think most people (me included) will copy-paste the workflow yaml anyway. Thanks!

**Comment by grouville** [comment]
> le (me included) will copy-paste the workflow yaml anyway. Thanks!

do you prefer appearing as `dagger-action` in the marketplace (as it is now) ? or `dagger-for-github` ?

**Comment by shykes** [comment]
For consistency, I would prefer `dagger-for-github`. Less different words to remember :)

**Pull request merged**
