### PR TITLE
rename dagger to dagger-cue

### LINKED ISSUE #78: Move `dagger` binary to `dagger-cue`
depends on:
- [ ] https://github.com/dagger/dagger/pull/4069

The CUE SDK has been moved to `dagger-cue` recently 
https://docs.dagger.io/sdk/cue/526369/install

### PR DESCRIPTION
**Pull request by marcosnils**
waiting on: 
- https://github.com/dagger/dagger/pull/4069

fixes #78

this will require releasing a new major version since it breaks backwards compat.

Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>

### CODE REVIEW

**Comment by jlongtine** [comment]
@gerhard I agree.

**Comment by jlongtine** [comment]
> Agree, I thought the `cue-sdk` branch had a way to build `dagger-cue` without all the new refactoring stuff in case we needed to ship a bugfix or something. If that's not the case, in this case this PR can be closed as IIUC, the current `cue-sdk` branch is not complete and is not intended to be used from source yet. Is that correct @jlongtine ?

The current `cue-sdk` branch contains the v0.2/Europa codebase. So, it _is intended_ to be used in its current state.

**Comment by marcosnils** [comment]
@jlongtine but I thought the `cue-sdk` branch also had all your in-progress work to migrate to cloak? Is that done already?

**Comment by jlongtine** [comment]
> @jlongtine but I thought the `cue-sdk` branch also had all your in-progress work to migrate to cloak? Is that done already?

Only on my fork. Hasn't been merged. Not done. There are engine features that aren't finished yet that cause some issues for some Europa features.

**Comment by marcosnils** [comment]
> Only on my fork. Hasn't been merged. Not done. There are engine features that aren't finished yet that cause some issues for some Europa features.

got it. In that case, leaving that Dockerifle there is useful in case we need to push a fix to Europa that someone might need in their CI which is using the `dagger-for-github` action. I think it's very unlikely to happen, but leaving the Dockerfile there doesn't hurt.

**Pull request merged**
