### PR TITLE
feat: support latest as a version and use it as the default input

### LINKED ISSUE #114: ✨ Support latest as the default option for the version input
### What are you trying to do?

I want to stay in sync with the latest version of Dagger while using the GitHub action. However, I have to explicitly set the version to `''`, which isn't a great developer experience. The `version` input should default to `latest` and reflect this in the script and documentation.

Many other GitHub actions use this approach.

### Why is this important to you?

Keeping in sync requires manual updates of my GitHub workflows or setting the version to `''`. If I am to be explicit, I would prefer to put the version as `latest` within my workflows.

### How are you currently working around this?

I have to manually update my workflows with the version of Dagger that I want.

### PR DESCRIPTION
**Pull request by purpleclay**
closes #114

### CODE REVIEW

**Comment by purpleclay** [comment]
This change has the added benefit of not needing to keep this repository in sync with each dagger release.

**Comment by jedevc** [comment]
cc @gerhard 

One thing I do like about the current setup is that if you pin this repo to a specific version/tag then it forces a specific dagger version - instead of needing to track multiple versions.

That said, I've seen `latest` as a pattern as well, specifically with the docker build actions - so maybe this is also viable.

**Comment by gerhard** [comment]
Thanks for contributing this @purpleclay!

The problem with defaulting to `latest` is that we could break pipelines out of the blue. `0.8.0` had several breaking changes, `0.9.0` had a few & both `0.10.0` & `0.11.0` changed fundamental aspects in how the CLI & the Engine work together.

I am all for adding `latest` as an explicit version value. Would that work @purpleclay?

**Comment by purpleclay** [comment]
> Thanks for contributing this @purpleclay!
> 
> The problem with defaulting to `latest` is that we could break pipelines out of the blue. `0.8.0` had several breaking changes, `0.9.0` had a few & both `0.10.0` & `0.11.0` changed fundamental aspects in how the CLI & the Engine work together.
> 
> I am all for adding `latest` as an explicit version value. Would that work @purpleclay?

@gerhard happy to make that change 👍

**Comment by purpleclay** [comment]
@gerhard I have made those changes now

**Comment by gerhard** [comment]
Looking at this now.

**Review by gerhard — APPROVED** [review]
👍 🚀

**Comment by gerhard** [comment]
Thank you @purpleclay 💪

This change is now available in the updated `v5` as well as the new [`v5.3.0`](https://github.com/dagger/dagger-for-github/releases/tag/v5.3.0)

**Pull request merged**
